# Generated by Django 3.0.2 on 2020-08-23 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('birthdate', models.DateTimeField()),
                ('admission_date', models.DateTimeField()),
                ('job_role', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='NaverProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navers.Naver')),
                ('projeto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='navers.Projeto')),
            ],
        ),
    ]
