# Generated by Django 3.0.2 on 2020-08-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naver',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
