# Generated by Django 3.0.2 on 2020-08-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navers', '0002_naver_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
